"""add_school_settings_and_school_it_role

Revision ID: c91e5e67d3f2
Revises: 2a615b0b9a09
Create Date: 2026-03-03 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c91e5e67d3f2"
down_revision: Union[str, None] = "2a615b0b9a09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS schools (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            address VARCHAR(500) NOT NULL,
            logo_url VARCHAR(1000),
            subscription_plan VARCHAR(100) NOT NULL DEFAULT 'free',
            subscription_start DATE NOT NULL DEFAULT CURRENT_DATE,
            subscription_end DATE,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS school_settings (
            school_id INTEGER PRIMARY KEY REFERENCES schools(id) ON DELETE CASCADE,
            primary_color VARCHAR(7) NOT NULL DEFAULT '#162F65',
            secondary_color VARCHAR(7) NOT NULL DEFAULT '#2C5F9E',
            accent_color VARCHAR(7) NOT NULL DEFAULT '#4A90E2',
            updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL
        )
        """
    )

    op.execute(
        """
        INSERT INTO schools (name, address, subscription_plan, subscription_start)
        SELECT 'Default School', 'Default Address', 'free', CURRENT_DATE
        WHERE NOT EXISTS (SELECT 1 FROM schools)
        """
    )

    op.execute(
        """
        INSERT INTO school_settings (school_id)
        SELECT s.id
        FROM schools s
        WHERE NOT EXISTS (
            SELECT 1 FROM school_settings ss WHERE ss.school_id = s.id
        )
        """
    )

    op.execute(
        """
        INSERT INTO roles (name)
        SELECT 'school_IT'
        WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'school_IT')
        """
    )


def downgrade() -> None:
    op.execute("DELETE FROM roles WHERE name = 'school_IT'")
    op.execute("DROP TABLE IF EXISTS school_settings")
    op.execute("DROP TABLE IF EXISTS schools")
